WIP: Migrate to GitLab CI
osbuild/koji-osbuild pull request #58
Opened 2021-07-16 09:49 UTC by atodorov

2021-07-16 09:56 UTC, atodorov commented
@gicmo, @ondrejbudai I believe this needs the ``secrets.SCHUTZBOT_SSH_KEY`` to be configured for this repository on GitHub.

2021-07-21 12:36 UTC, atodorov commented
I think this is blocked by the failures in #57 for Fedora 34 and RHEL 8. 

@ondrejbudai any chance you can finish the work on #57 soon or is it blocked by something else ?

2021-07-28 08:48 UTC, ondrejbudai requested changes
Thanks! Few comments inline.

2021-07-28 08:48 UTC, ondrejbudai commented on .gitlab-ci.yml
> +    - schutzbot/run_cloud_cleaner.sh
`after_script` is overwritten in all jobs derived from `.terraform`, let's just remove this block.

2021-07-28 08:48 UTC, ondrejbudai commented on schutzbot/deploy.sh
> +GIT_COMMIT="${GIT_COMMIT:-${CI_COMMIT_SHA}}"
can we just `s/GIT_COMMIT/CI_COMMIT_SHA/` in the whole file instead of defining an extra variable?

2021-07-28 08:48 UTC, ondrejbudai commented on schutzbot/run_cloud_cleaner.sh
> +#!/bin/bash
`cloud-cleaner` is not available, nor needed in this repository.

2021-07-28 08:56 UTC, ondrejbudai approved these changes

2021-07-29 09:19 UTC, merged